### PR TITLE
Fix Twitch API fetch with for the new Twitch API version.

### PR DESCRIPTION
**Pull request by alexandre1985**
Added a config directory and a token.conf file

### CODE REVIEW

**Comment by buzz** [comment]
Thanks for the effort to revive this project. Unfortunately your patch is not working:

```
creating directory...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "venv/bin/twitch-indicator.py", line 338, in refresh_streams
    self.USER_ID = self.tw.get_user_id(self.settings.get_string('twitch-username'))
  File "venv/bin/twitch-indicator.py", line 142, in get_user_id
    resp = self.get_api_decoded_response('users?login=' + username)
  File "venv/bin/twitch-indicator.py", line 151, in get_api_decoded_response
    access_code = get_api_access_token()
  File "venv/bin/twitch-indicator.py", line 510, in get_api_access_token
    access_token_response = get_api_access_token_from_web()
  File "venv/bin/twitch-indicator.py", line 470, in get_api_access_token_from_web
    req = Request(TWITCH_ID_URL, urlencode(headers).encode())
NameError: name 'urlencode' is not defined
```

**Comment by alexandre1985** [comment]
weird. on my machine it works. I am gonna check it out

**Comment by buzz** [comment]
> weird. on my machine it works. I am gonna check it out

Nope. It does not as `urlencode` is not defined.

**Comment by alexandre1985** [comment]
on my machine it does. that is what is weird :stuck_out_tongue:

**Comment by buzz** [comment]
> on my machine it does. that is what is weird

That's somehow funny. But you're doing something wrong here ;)
As I cannot see what you're doing on your machine, I'm unable to tell what you are doing wrong.

Python is smart enough to tell you exactly what is wrong with your code: `NameError: name 'urlencode' is not defined`
If I look at your code I can tell that Python must throw an error. Because you are calling the function `urlencode` which is not defined anywhere in your code.

**Comment by alexandre1985** [comment]
yeah @buzz I know that. Thank you. What I was amazed at was that running `./twitch-indicator.py` gave me no error at all, which makes no sense.

`twitch-indicator.py` opened up the app in my system tray and it fetched all of my streams, telling me which ones where live.

Now it should be resolved on everyones machine (I guess) :face_with_head_bandage: 

**update:** please do give me some feedback @buzz

**Comment by buzz** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "venv/bin/twitch-indicator.py", line 339, in refresh_streams
    self.USER_ID = self.tw.get_user_id(self.settings.get_string('twitch-username'))
  File "venv/bin/twitch-indicator.py", line 143, in get_user_id
    resp = self.get_api_decoded_response('users?login=' + username)
  File "venv/bin/twitch-indicator.py", line 152, in get_api_decoded_response
    access_code = get_api_access_token()
  File "venv/bin/twitch-indicator.py", line 513, in get_api_access_token
    write_access_token_to_file(access_token_response)
  File "venv/bin/twitch-indicator.py", line 499, in write_access_token_to_file
    expire_date = datetime.now() + datetime.timedelta(seconds=response['expires_in'])
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
```

I'm very sorry. But I do not have the time to debug your code.

Please, do some thorough testing on your patches before submitting PRs.

I'll close the PR for now.

**Comment by alexandre1985** [comment]
Well, your lack of care for the program I guess it is everyones loss. On my machine it works. Anyway, I say thanks to you

**Comment by buzz** [comment]
> Well, your lack of care for the program I guess it is everyones loss.

You're barking up the wrong tree, mate... :weary: 

https://aur.archlinux.org/packages/twitch-indicator/#comment-667647

> On my machine it works.

Still nope.

> Anyway, I say thanks to you

Sure. No problem.

**Pull request closed without merging**
