### PR TITLE
Add streams to top menu directly

### PR DESCRIPTION
**Pull request by Keelhauled**
Add streams to top menu directly and change the title and id of the AppIndicator to be more appropriate.

Hopefully you consider this a full improvement over the old style so there is no need for an option.

### CODE REVIEW

**Comment by LizzieA69** [comment]
I use your app on Manjaro-ARM XFCE on a Raspberry Pi 400 and with the new update it is fully running again for me. Thank you

**Comment by buzz** [comment]
Um. I don't know if that's a good idea...

When you got a long list of streams, you'd have to scroll endlessly just to reach "Settings" or "Quit" menu entry. That's why there was a sub menu in the first place.

Also, the entries are in the wrong order now for me.

**Comment by Keelhauled** [comment]
That must be a LOT of streamers lol, but i'd say its worth the quicker access to the list.
That last commit fixed the order.

**Comment by Keelhauled** [comment]
I see your theme uses much more space for each entry though so that might get big fast.

**Comment by LizzieA69** [comment]
I think the box showing live streamers should be a fixed size with an arrow buttons to help you scroll through them I have a long list of streamers I follow so in setting I'm scrolling

**Comment by Keelhauled** [comment]
AppIndicator doesn't seem to have any built in way to do a scrollbar like that

**Comment by buzz** [comment]
> That must be a LOT of streamers lol, but i'd say its worth the quicker access to the list.

I really like the idea, but it's more difficult unfortunately. One click less does not warrant the "Settings" and "Quit" menu entries being buried under all live channels. New users wouldn't even know where to find the settings and start to spam the issue tracker. Also, we'd loose total count of live channels which gets printed on the sub menu. Also this does render the application unusable for people using screen readers...

Still, I think this could be beneficial. So, I propose creating an opt-in option "Show live channels on first menu level" in the settings.

> That last commit fixed the order.

Nope, in fact I used commit b7e50607201dd73082522ad48316f98358900ff0 which I first had to rebase on the current master. That one has a messed up channel order.

**Comment by buzz** [comment]
> I think the box showing live streamers should be a fixed size with an arrow buttons to help you scroll through them I have a long list of streamers I follow so in setting I'm scrolling

@Keelhauled is right. AppIndicator is based on [SNI](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/). In fact they don't allow custom widgets to be displayed. They deliberately limit the indicators to show only simple menus to create a more consistent user experience.

**Comment by Keelhauled** [comment]
> Nope, in fact I used commit https://github.com/buzz/twitch-indicator/commit/b7e50607201dd73082522ad48316f98358900ff0 which I first had to rebase on the current master. That one has a messed up channel order.

Just another KDE grievance then, I wonder if it would better to switch away from AppIndicator to some more modern tray icon api to have a better experience for KDE.

**Comment by Keelhauled** [comment]
And I'll add the option :+1:

**Comment by Keelhauled** [comment]
How does the order look now?

**Comment by buzz** [comment]
Please follow the [Fork and pull model](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models#fork-and-pull-model).

In particular:

- You are working on an old version of the program. Rebase all work on current master.
- Create separate PRs for separate features (using [feature branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches#about-branches)).
- Use [atomic commits](https://dev.to/paulinevos/atomic-commits-will-help-you-git-legit-35i7).

Thank you

**Comment by Keelhauled** [comment]
I'd be down for that if this wasn't some 500 line python app with barely any activity. Is this really necessary?
And there aren't even any merge conflicts.

**Comment by buzz** [comment]
> I'd be down for that if this wasn't some 500 line python app with barely any activity. 

No problem

**Comment by Keelhauled** [comment]
This can't be the real reason you are closing this. Come on you can tell me.

**Comment by Keelhauled** [comment]
Too lazy to maintain this?

**Comment by Keelhauled** [comment]
Like, it's such a simple PR to even make a fuss about.

**Comment by buzz** [comment]
I'm not up for discussions. Go somewhere else please, thank you.

**Pull request closed without merging**
